elements = {
--         CPU0
{
    kind = 'ring_graph',
    center = {x = 35, y = 350},
    radius = 20,
	conky_value = 'cpu cpu0',
	max_value = 10,
	critical_threshold = 9,
	bar_color = '0x50fa7b',
	bar_alpha = 1.0,
	bar_thickness = 8,
	background_color = '0x555555',
	background_alpha = 1.0,
	background_thickness = 8,
	change_color_on_critical = false,
	change_alpha_on_critical = false,
	change_thickness_on_critical = false,
	background_color_critical = '0x000000',
	background_alpha_critical = 1.0,
	background_thickness_critical = 8,
	bar_color_critical = '0x000000',
	bar_alpha_critical = 1,
	bar_thickness_critical = 8,
	start_angle = 180,
	end_angle = 270,
	graduated = false,
	number_graduation = 10,
	angle_between_graduation = 10,
},

--         CPU1
{
    kind = 'ring_graph',
    center = {x = 35, y = 350},
    radius = 20,
	conky_value = 'cpu cpu1',
	max_value = 10,
	critical_threshold = 9,
	bar_color = '0x50fa7b',
	bar_alpha = 1.0,
	bar_thickness = 8,
	background_color = '0x555555',
	background_alpha = 1.0,
	background_thickness = 8,
	change_color_on_critical = false,
	change_alpha_on_critical = false,
	change_thickness_on_critical = false,
	background_color_critical = '0x000000',
	background_alpha_critical = 1.0,
	background_thickness_critical = 8,
	bar_color_critical = '0x000000',
	bar_alpha_critical = 1,
	bar_thickness_critical = 8,
	start_angle = 270,
	end_angle = 360,
	graduated = false,
	number_graduation = 10,
	angle_between_graduation = 10,
},

--         CPU2
{
    kind = 'ring_graph',
    center = {x = 35, y = 350},
    radius = 20,
	conky_value = 'cpu cpu2',
	max_value = 10,
	critical_threshold = 9,
	bar_color = '0x50fa7b',
	bar_alpha = 1.0,
	bar_thickness = 8,
	background_color = '0x555555',
	background_alpha = 1.0,
	background_thickness = 8,
	change_color_on_critical = false,
	change_alpha_on_critical = false,
	change_thickness_on_critical = false,
	background_color_critical = '0x000000',
	background_alpha_critical = 1.0,
	background_thickness_critical = 8,
	bar_color_critical = '0x000000',
	bar_alpha_critical = 1,
	bar_thickness_critical = 8,
	start_angle = 1,
	end_angle = 90,
	graduated = false,
	number_graduation = 10,
	angle_between_graduation = 10,
},

--         CPU0
{
    kind = 'ring_graph',
    center = {x = 35, y = 350},
    radius = 20,
	conky_value = 'cpu cpu3',
	max_value = 10,
	critical_threshold = 9,
	bar_color = '0x50fa7b',
	bar_alpha = 1.0,
	bar_thickness = 8,
	background_color = '0x555555',
	background_alpha = 1.0,
	background_thickness = 8,
	change_color_on_critical = false,
	change_alpha_on_critical = false,
	change_thickness_on_critical = false,
	background_color_critical = '0x000000',
	background_alpha_critical = 1.0,
	background_thickness_critical = 8,
	bar_color_critical = '0x000000',
	bar_alpha_critical = 1,
	bar_thickness_critical = 8,
	start_angle = 90,
	end_angle = 180,
	graduated = false,
	number_graduation = 10,
	angle_between_graduation = 10,
},

--  CPU Text
{
kind = 'static_text',
from = {x=100, y=355},
text = 'CPU Usage',
color = '0x50fa7b',
rotation_angle = 360,
font_size = 18,
font = 'Product Sans',
bold = false,
italic = false,
alpha = 1.0,
},

-- NEXT SECTION

{
    kind = 'ring_graph',
    center = {x = 35, y = 350},
    radius = 30,
	conky_value = 'memperc',
	max_value = 100,
	critical_threshold = 90,
	bar_color = '0xff79c6',
	bar_alpha = 1.0,
	bar_thickness = 8,
	background_color = '0x555555',
	background_alpha = 1.0,
	background_thickness = 8,
	change_color_on_critical = false,
	change_alpha_on_critical = false,
	change_thickness_on_critical = false,
	background_color_critical = '0x000000',
	background_alpha_critical = 1.0,
	background_thickness_critical = 8,
	bar_color_critical = '0x000000',
	bar_alpha_critical = 1,
	bar_thickness_critical = 8,
	start_angle = 0,
	end_angle = 360,
	graduated = false,
	number_graduation = 10,
	angle_between_graduation = 10,
},

--  RAM
{
kind = 'static_text',
from = {x=100, y=375},
text = 'RAM Usage',
color = '0xff79c6',
rotation_angle = 360,
font_size = 18,
font = 'Product Sans',
bold = false,
italic = false,
alpha = 1.0,
},

--  Glance

{
kind = 'static_text',
from = {x=100, y=325},
text = 'Visual Glance',
color = '0xffffff',
rotation_angle = 360,
font_size = 18,
font = 'Product Sans',
bold = true,
italic = false,
alpha = 1.0,
},

}
